export { default as Login } from './Login'
export { default as SignUp } from './SignUp'
export { default as ResetPassword } from './ResetPassword'
export { default as Dashboard } from './Dashboard'
export { default as UserForm } from './UserForm'
